CREATE DATABASE LIVRARIA;

CREATE TABLE USUARIO (
USUARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(45) UNIQUE NOT NULL,
SENHA VARCHAR(15) NOT NULL,
SALDO INTEGER NOT NULL
);

CREATE TABLE LIVRO (
LIVRO_ID INT PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR(100) NOT NULL,
SUB_TITULO VARCHAR(100) NOT NULL,
AUTOR VARCHAR(50)NOT NULL,
EDICAO VARCHAR(50) NOT NULL,
GENERO VARCHAR(50) NOT NULL,
ISBN VARCHAR(30) NOT NULL
);

CREATE TABLE LISTA_DE_DESEJO (
CONSTRAINT USUARIO_ID PRIMARY KEY(USUARIO),
CONSTRAINT LIVRO_ID PRIMARY KEY(LIVRO),
DATA_DE_PEDIDO TIMESTAMP NOT NULL
);

CREATE TABLE LIVRO_DO_USUARIO (
CONSTRAINT USUARIO_ID PRIMARY KEY(USUARIO),
CONSTRAINT LIVRO_ID PRIMARY KEY(LIVRO),
DATA_DE_INCLUSAO TIMESTAMP NOT NULL
);