CREATE TABLE USUARIO (
USUARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(25) NOT NULL,
EMAIL VARCHAR(25) NOT NULL,
SENHA VARCHAR(10) NOT NULL,
SALDO INTEGER NOT NULL
);

CREATE TABLE LIVRO (
LIVRO_ID INT PRIMARY KEY AUTO_INCREMENT,
NOMEDOLIVRO VARCHAR(20) NOT NULL,
AUTOR VARCHAR(25)NOT NULL,
EDICAO VARCHAR(10) NOT NULL,
ISBN VARCHAR(20) NOT NULL
);

CREATE TABLE LISTADEDESEJO (
CONSTRAINT USUARIO_ID PRIMARY KEY(USUARIO),
CONSTRAINT LIVRO_ID PRIMARY KEY(LIVRO),
DATADEPEDIDO TIMESTAMP NOT NULL
);

CREATE TABLE LIVRODOUSUARIO (
CONSTRAINT USUARIO_ID PRIMARY KEY(USUARIO),
CONSTRAINT LIVRO_ID PRIMARY KEY(LIVRO),
DATADEINCLUSAO TIMESTAMP NOT NULL,
GENERO VARCHAR(25) NOT NULL
);